### ISSUE TITLE
Preview broken

### ISSUE THREAD

**Issue by poly2it** [HPsaucii/zed-editor-flake#30]
The breakage was introduced in ea5a8567aebe608791f050e379b808afb7135066.

```
error: Cannot build '/nix/store/fs17n7gkdym4ykg312p1v5i2fp0pcr20-zed-editor-0.194.3-pre.drv'.
       Reason: builder failed with exit code 101.
       Output paths:
         /nix/store/dj2gs4zxfc45qc0mbdkv1j8myd9za7p9-zed-editor-0.194.3-pre
         /nix/store/s29kmzhwfm9pnwlp4b0qs47cl1rha3kf-zed-editor-0.194.3-pre-remote_server
       Last 25 log lines:
       >    Compiling web_search_providers v0.1.0 (/build/source/crates/web_search_providers)
       > error[E0658]: `let` expressions in this position are unstable
       >    --> crates/dap_adapters/src/codelldb.rs:368:20
       >     |
       > 368 |                 if let Some(config) = json_config.as_object_mut()
       >     |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
       >     |
       >     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
       >
       > error[E0658]: `let` expressions in this position are unstable
       >    --> crates/dap_adapters/src/codelldb.rs:369:24
       >     |
       > 369 |                       && let Some(source_languages) = config.get("sourceLanguages").filter(|value| {
       >     |  ________________________^
       > 370 | |                         value
       > 371 | |                             .as_array()
       > 372 | |                             .map_or(false, |array| array.iter().all(Value::is_string))
       > 373 | |                     })
       >     | |______________________^
       >     |
       >     = note: see issue #53667 <https://github.com/rust-lang/rust/issues/53667> for more information
       >
       > For more information about this error, try `rustc --explain E0658`.
       > error: could not compile `dap_adapters` (lib) due to 2 previous errors
       > warning: build failed, waiting for other jobs to finish...
       For full logs, run:
         nix log /nix/store/fs17n7gkdym4ykg312p1v5i2fp0pcr20-zed-editor-0.194.3-pre.drv
error: Cannot build '/nix/store/kc4qjxfq8wab9sc50iljdyaghjng3sjc-zed-editor.drv'.
```:

**Comment by HPsaucii** [comment]
@poly2it This is an issue with the upstream release. Please create an issue at https://github.com/zed-industries/zed instead

**Comment by poly2it** [comment]
> [@poly2it](https://github.com/poly2it) This is an issue with the upstream release. Please create an issue at https://github.com/zed-industries/zed instead

I'm pretty sure we could fix this by changing the toolchain in use.

**Comment by HPsaucii** [comment]
@poly2it Working on a fix for this now. To be clear:
1. I no longer use nixos
2. This flake was designed to be used while upstream sorted their problems out

**Comment by HPsaucii** [comment]
> Very thoughtful, thank you. May I ask why you stopped using NixOS? Do you not use Nix anymore either?

Mostly just because i don't think NixOS is really ready. When trying to do compiling / play certain games (especially modded ones), i would consistently run out of file descriptors with no remedy. I've flipped between NixOS and Gentoo (the distro I am sending this from) over the years, I'm just in my gentoo arc at the minute.

In terms of using nix, It's a bit of a pain to set up on gentoo with musl + llvm, doable, but a pain. I probably will get it setup soon™️ but it's not my priority as of right now.
